runtime: nodejs16
env_variables:
  NODE_ENV: production
  PROJECT_ID: edu-classroom-analytics
  INSTANCE_UNIX_SOCKET: /cloudsql/edu-classroom-analytics:us-central1:edu-analytics
  DB_USER: root
  DB_PASS: (.Y<A-a3}~$Klp""
  DB_NAME: edu-analytics
  STD_PORTAL: https://edu-classroom-analytics-dqun6rptiq-uc.a.run.app
beta_settings:
  cloud_sql_instances: edu-classroom-analytics:us-central1:edu-analytics