apiVersion: apps/v1
kind: Deployment
metadata:
  name: citizen-360-app
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: citizen-360-app
        image: citizen-360-app
        imagePullPolicy: Always
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: PROJECT_ID
        - name: EXTERNAL_DATA_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: EXTERNAL_DATA_PROJECT_ID
